### ISSUE TITLE
Doc example

### ISSUE THREAD

**Issue by EzpzCraft** [Snapizz/d2protocol#2]
Hi !
I just tries the code sample provided in the README, but I got an error with this instruction:
`message.pack(wrapper);`

It seems to be a problem with byteArray2:

> RangeError: index out of range
    at checkInt (buffer.js:892:11)
    at Buffer.writeInt8 (buffer.js:1048:5)
    at ByteArray.writeByte (.../node_modules/d2protocol/node_modules/bytearray2/lib/bytearray.js:191:28)
    at CustomDataWrapper.writeByte (.../node_modules/d2protocol/lib/protocol.js:384:24)
    at HelloConnectMessage.serializeAs_HelloConnectMessage (.../node_modules/d2protocol/lib/protocol.js:3460:24)
    at HelloConnectMessage.serialize (.../node_modules/d2protocol/lib/protocol.js:3453:18)
    at HelloConnectMessage.pack (.../node_modules/d2protocol/lib/protocol.js:3446:18)
    at Object.<anonymous> (.../Main.js:14:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

So if the repository is still active, does someone have an idea how to solve it ?

**Comment by Snapizz** [comment]
try to update bytearray2 to latest.

you have to know that package is no longer updated from current D2 version

**Comment by EzpzCraft** [comment]
Thank you for your response,
I'm using the version 2.0.1 of bytearray2 (which should be the latest, right?)

I dig a bit further and found that the problem only occurs when packing messages containing arrays of more than 0 element.

For example:

```
var buff = new ByteArray();
var wrapper = new Protocol.CustomDataWrapper(buff);
var message = new Protocol.HelloConnectMessage();
message.key = [1]; // Do not work except if message.key = []
message.salt = 'salt...';
message.pack(wrapper);
wrapper.position = 0;
console.log( Protocol.MessageReceiver.parse(wrapper) );
```

From what I have tested, it only happen for the serialization, not the deserialization.
